USE BankDB

SELECT CUSTOMER.CustomerName, CUSTOMER.CustomerID, ACCOUNT.Balance, ACCOUNT.Date
FROM CUSTOMER
Inner Join ACCOUNT on
CUSTOMER.AccountNR = ACCOUNT.AccountNR
WHERE DATE ='08/10/2018'
ORDER BY CUSTOMER.CustomerID;
